/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CtaBlock = {
  _type: "ctaBlock";
  eyebrow?: string;
  title?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  body?: string;
  ctaLabel?: string;
  note?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  occasion?: string;
  orderRank?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: CategoryReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projects?: {
    eyebrow?: string;
    title?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    blurb?: string;
    ctaLabel?: string;
    ctaHref?: string;
  };
  ctaPrimary?: CtaBlock;
  testimonials?: {
    eyebrow?: string;
    title?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    blurb?: string;
    background?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  ctaClosing?: CtaBlock;
  contact?: {
    eyebrow?: string;
    title?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  stats?: Array<{
    value?: number;
    suffix?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  quoteEyebrow?: string;
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  attribution?: string;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  background?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cutouts?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  credits?: Array<{
    title?: string;
    meta?: string;
    _type: "credit";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  whatsappNumber?: string;
  whatsappLabel?: string;
  bookingLabel?: string;
  email?: string;
  instagram?: string;
  location?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | CtaBlock
  | Testimonial
  | CategoryReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Home
  | About
  | Hero
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: {  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    siteName, whatsappNumber, whatsappLabel, bookingLabel, email, instagram, location  },  "hero": *[_type == "hero" && _id == "hero"][0]{    headline,    background{  alt,  hotspot,  crop,  asset->{ _id, metadata { lqip, dimensions { width, height } } }},    cutouts[]{  alt,  hotspot,  crop,  asset->{ _id, metadata { lqip, dimensions { width, height } } }},    credits[]{ _key, title, meta }  },  "about": *[_type == "about" && _id == "about"][0]{    eyebrow,    stats[]{ _key, value, suffix, label },    quoteEyebrow, quote, attribution  },  "home": *[_type == "home" && _id == "home"][0]{    projects { eyebrow, title, blurb, ctaLabel, ctaHref },    ctaPrimary{ eyebrow, title, body, ctaLabel, note },    testimonials { eyebrow, title, blurb, background{  alt,  hotspot,  crop,  asset->{ _id, metadata { lqip, dimensions { width, height } } }} },    ctaClosing{ eyebrow, title, body, ctaLabel, note },    contact { eyebrow, title }  },  "projects": *[_type == "project" && defined(image.asset)] | order(orderRank) {    _id, title, "category": category->title, image{  alt,  hotspot,  crop,  asset->{ _id, metadata { lqip, dimensions { width, height } } }}  },  "testimonials": *[_type == "testimonial"] | order(orderRank) {    _id, quote, name, occasion  }}
export type HOME_PAGE_QUERY_RESULT = {
  settings: {
    siteName: string | null;
    whatsappNumber: string | null;
    whatsappLabel: string | null;
    bookingLabel: string | null;
    email: string | null;
    instagram: string | null;
    location: string | null;
  } | null;
  hero: {
    headline: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    background: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    cutouts: Array<{
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    }> | null;
    credits: Array<{
      _key: string;
      title: string | null;
      meta: string | null;
    }> | null;
  } | null;
  about: {
    eyebrow: string | null;
    stats: Array<{
      _key: string;
      value: number | null;
      suffix: string | null;
      label: string | null;
    }> | null;
    quoteEyebrow: string | null;
    quote: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    attribution: string | null;
  } | null;
  home: {
    projects: {
      eyebrow: string | null;
      title: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      blurb: string | null;
      ctaLabel: string | null;
      ctaHref: string | null;
    } | null;
    ctaPrimary: {
      eyebrow: string | null;
      title: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      body: string | null;
      ctaLabel: string | null;
      note: string | null;
    } | null;
    testimonials: {
      eyebrow: string | null;
      title: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      blurb: string | null;
      background: {
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
    ctaClosing: {
      eyebrow: string | null;
      title: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      body: string | null;
      ctaLabel: string | null;
      note: string | null;
    } | null;
    contact: {
      eyebrow: string | null;
      title: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    } | null;
  } | null;
  projects: Array<{
    _id: string;
    title: string | null;
    category: string | null;
    image: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      };
    };
  }>;
  testimonials: Array<{
    _id: string;
    quote: string | null;
    name: string | null;
    occasion: string | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: SEO_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  siteName,  seo { title, description, "ogImage": ogImage.asset->url }}
export type SEO_QUERY_RESULT = {
  siteName: string | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: string | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    siteName, whatsappNumber, whatsappLabel, bookingLabel, email, instagram, location\n  },\n  "hero": *[_type == "hero" && _id == "hero"][0]{\n    headline,\n    background{\n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, metadata { lqip, dimensions { width, height } } }\n},\n    cutouts[]{\n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, metadata { lqip, dimensions { width, height } } }\n},\n    credits[]{ _key, title, meta }\n  },\n  "about": *[_type == "about" && _id == "about"][0]{\n    eyebrow,\n    stats[]{ _key, value, suffix, label },\n    quoteEyebrow, quote, attribution\n  },\n  "home": *[_type == "home" && _id == "home"][0]{\n    projects { eyebrow, title, blurb, ctaLabel, ctaHref },\n    ctaPrimary{ eyebrow, title, body, ctaLabel, note },\n    testimonials { eyebrow, title, blurb, background{\n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, metadata { lqip, dimensions { width, height } } }\n} },\n    ctaClosing{ eyebrow, title, body, ctaLabel, note },\n    contact { eyebrow, title }\n  },\n  "projects": *[_type == "project" && defined(image.asset)] | order(orderRank) {\n    _id, title, "category": category->title, image{\n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, metadata { lqip, dimensions { width, height } } }\n}\n  },\n  "testimonials": *[_type == "testimonial"] | order(orderRank) {\n    _id, quote, name, occasion\n  }\n}': HOME_PAGE_QUERY_RESULT;
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n  siteName,\n  seo { title, description, "ogImage": ogImage.asset->url }\n}': SEO_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
